/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.spacecup.form;

import br.com.spacecup.dao.AdministradorDAO;
import br.com.spacecup.modelo.Aluno;
import br.com.spacecup.modelo.Equipe;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class FormCadastrar extends javax.swing.JFrame {

    private Color corFiap = new Color(237, 25, 93);

    public FormCadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoSpaceCup = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        lblTurma = new javax.swing.JLabel();
        txtNomeGrupo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblSenha = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblComponente1 = new javax.swing.JLabel();
        txtComponente1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblRM1 = new javax.swing.JLabel();
        txtRM1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cbbTurma = new javax.swing.JComboBox<>();
        lblNomeGrupo = new javax.swing.JLabel();
        lblObrigatorio = new javax.swing.JLabel();
        pwdSenha = new javax.swing.JPasswordField();
        lblComponente2 = new javax.swing.JLabel();
        txtComponente2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        lblRM2 = new javax.swing.JLabel();
        txtRM2 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        lblComponente3 = new javax.swing.JLabel();
        txtComponente3 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        lblRM3 = new javax.swing.JLabel();
        txtRM3 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        lblComponente4 = new javax.swing.JLabel();
        txtComponente4 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        lblRM4 = new javax.swing.JLabel();
        txtRM4 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        lblComponente5 = new javax.swing.JLabel();
        txtComponente5 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        lblRM5 = new javax.swing.JLabel();
        txtRM5 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        Voltar = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JPanel();
        lblCadastrar = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        lblLimpar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        logoSpaceCup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/logo.png"))); // NOI18N

        lblCadastro.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastro.setText("CADASTRO");

        lblTurma.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTurma.setForeground(new java.awt.Color(255, 255, 255));
        lblTurma.setText("TURMA");

        txtNomeGrupo.setBackground(new java.awt.Color(0, 0, 0));
        txtNomeGrupo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNomeGrupo.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeGrupo.setBorder(null);
        txtNomeGrupo.setSelectionColor(new java.awt.Color(234, 25, 93));
        txtNomeGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeGrupoFocusLost(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lblSenha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("SENHA*");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lblComponente1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente1.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente1.setText("NOME DO COMPONENTE 1*");

        txtComponente1.setBackground(new java.awt.Color(0, 0, 0));
        txtComponente1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtComponente1.setForeground(new java.awt.Color(255, 255, 255));
        txtComponente1.setBorder(null);
        txtComponente1.setSelectionColor(new java.awt.Color(234, 25, 93));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        lblRM1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM1.setForeground(new java.awt.Color(255, 255, 255));
        lblRM1.setText("RM*");

        txtRM1.setBackground(new java.awt.Color(0, 0, 0));
        txtRM1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRM1.setForeground(new java.awt.Color(255, 255, 255));
        txtRM1.setBorder(null);
        txtRM1.setSelectionColor(new java.awt.Color(234, 25, 93));
        txtRM1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRM1FocusLost(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        cbbTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2SIA", "2SIB", "2SIR", "2SIS", "2SIT", "3ECA", "3ECR", "3ECS", "3EPR" }));

        lblNomeGrupo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblNomeGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeGrupo.setText("NOME DO GRUPO*");

        lblObrigatorio.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblObrigatorio.setForeground(new java.awt.Color(255, 255, 255));
        lblObrigatorio.setText("*Obrigatório");

        pwdSenha.setBackground(new java.awt.Color(0, 0, 0));
        pwdSenha.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pwdSenha.setForeground(new java.awt.Color(255, 255, 255));
        pwdSenha.setBorder(null);
        pwdSenha.setSelectionColor(new java.awt.Color(234, 25, 93));

        lblComponente2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente2.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente2.setText("NOME DO COMPONENTE 2*");

        txtComponente2.setBackground(new java.awt.Color(0, 0, 0));
        txtComponente2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtComponente2.setForeground(new java.awt.Color(255, 255, 255));
        txtComponente2.setBorder(null);
        txtComponente2.setSelectionColor(new java.awt.Color(234, 25, 93));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));

        lblRM2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM2.setForeground(new java.awt.Color(255, 255, 255));
        lblRM2.setText("RM*");

        txtRM2.setBackground(new java.awt.Color(0, 0, 0));
        txtRM2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRM2.setForeground(new java.awt.Color(255, 255, 255));
        txtRM2.setBorder(null);
        txtRM2.setSelectionColor(new java.awt.Color(234, 25, 93));
        txtRM2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRM2FocusLost(evt);
            }
        });

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));

        lblComponente3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente3.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente3.setText("NOME DO COMPONENTE 3*");

        txtComponente3.setBackground(new java.awt.Color(0, 0, 0));
        txtComponente3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtComponente3.setForeground(new java.awt.Color(255, 255, 255));
        txtComponente3.setBorder(null);
        txtComponente3.setSelectionColor(new java.awt.Color(234, 25, 93));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));

        lblRM3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM3.setForeground(new java.awt.Color(255, 255, 255));
        lblRM3.setText("RM*");

        txtRM3.setBackground(new java.awt.Color(0, 0, 0));
        txtRM3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRM3.setForeground(new java.awt.Color(255, 255, 255));
        txtRM3.setBorder(null);
        txtRM3.setSelectionColor(new java.awt.Color(234, 25, 93));
        txtRM3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRM3FocusLost(evt);
            }
        });

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));

        lblComponente4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente4.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente4.setText("NOME DO COMPONENTE 4");

        txtComponente4.setBackground(new java.awt.Color(0, 0, 0));
        txtComponente4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtComponente4.setForeground(new java.awt.Color(255, 255, 255));
        txtComponente4.setBorder(null);
        txtComponente4.setSelectionColor(new java.awt.Color(234, 25, 93));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));

        lblRM4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM4.setForeground(new java.awt.Color(255, 255, 255));
        lblRM4.setText("RM");

        txtRM4.setBackground(new java.awt.Color(0, 0, 0));
        txtRM4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRM4.setForeground(new java.awt.Color(255, 255, 255));
        txtRM4.setBorder(null);
        txtRM4.setSelectionColor(new java.awt.Color(234, 25, 93));
        txtRM4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRM4FocusLost(evt);
            }
        });

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));

        lblComponente5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente5.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente5.setText("NOME DO COMPONENTE 5");

        txtComponente5.setBackground(new java.awt.Color(0, 0, 0));
        txtComponente5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtComponente5.setForeground(new java.awt.Color(255, 255, 255));
        txtComponente5.setBorder(null);
        txtComponente5.setSelectionColor(new java.awt.Color(234, 25, 93));

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));

        lblRM5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM5.setForeground(new java.awt.Color(255, 255, 255));
        lblRM5.setText("RM");

        txtRM5.setBackground(new java.awt.Color(0, 0, 0));
        txtRM5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRM5.setForeground(new java.awt.Color(255, 255, 255));
        txtRM5.setBorder(null);
        txtRM5.setSelectionColor(new java.awt.Color(234, 25, 93));
        txtRM5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRM5FocusLost(evt);
            }
        });

        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltar.png"))); // NOI18N
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(237, 25, 93));
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });

        lblCadastrar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrar.setText("CADASTRAR");

        javax.swing.GroupLayout btnCadastrarLayout = new javax.swing.GroupLayout(btnCadastrar);
        btnCadastrar.setLayout(btnCadastrarLayout);
        btnCadastrarLayout.setHorizontalGroup(
            btnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnCadastrarLayout.setVerticalGroup(
            btnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnLimpar.setBackground(new java.awt.Color(237, 25, 93));
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
        });

        lblLimpar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpar.setText("LIMPAR");

        javax.swing.GroupLayout btnLimparLayout = new javax.swing.GroupLayout(btnLimpar);
        btnLimpar.setLayout(btnLimparLayout);
        btnLimparLayout.setHorizontalGroup(
            btnLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLimparLayout.createSequentialGroup()
                .addComponent(lblLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnLimparLayout.setVerticalGroup(
            btnLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Voltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(logoSpaceCup)
                        .addGap(30, 30, 30)
                        .addComponent(lblCadastro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNomeGrupo)
                        .addGap(220, 220, 220)
                        .addComponent(lblTurma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(cbbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblSenha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblComponente1)
                        .addGap(139, 139, 139)
                        .addComponent(lblRM1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtComponente1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRM1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblComponente2)
                        .addGap(139, 139, 139)
                        .addComponent(lblRM2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtComponente2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRM2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblComponente3)
                        .addGap(139, 139, 139)
                        .addComponent(lblRM3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblComponente4)
                        .addGap(146, 146, 146)
                        .addComponent(lblRM4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtComponente4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRM4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblComponente5)
                        .addGap(146, 146, 146)
                        .addComponent(lblRM5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtComponente5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRM5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblObrigatorio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtComponente3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRM3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Voltar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoSpaceCup)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCadastro)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeGrupo)
                    .addComponent(lblTurma))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblSenha)
                .addGap(13, 13, 13)
                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComponente1)
                    .addComponent(lblRM1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComponente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComponente2)
                    .addComponent(lblRM2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComponente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComponente3)
                    .addComponent(lblRM3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComponente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComponente4)
                    .addComponent(lblRM4))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComponente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComponente5)
                    .addComponent(lblRM5))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComponente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblObrigatorio)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        FormLogin fl = new FormLogin();
        this.dispose();
        fl.setVisible(true);
    }//GEN-LAST:event_VoltarMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        limpar();
    }//GEN-LAST:event_btnLimparMouseClicked

    private void limpar() {
        txtNomeGrupo.setText("");
        pwdSenha.setText("");
        txtComponente1.setText("");
        txtRM1.setText("");
        txtComponente2.setText("");
        txtRM2.setText("");
        txtComponente3.setText("");
        txtRM3.setText("");
        txtComponente4.setText("");
        txtRM4.setText("");
        txtComponente5.setText("");
        txtRM5.setText("");
    }

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltarfocus.png"));
        Voltar.setIcon(icon);
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltar.png"));
        Voltar.setIcon(icon);
    }//GEN-LAST:event_VoltarMouseExited

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        btnLimpar.setBackground(Color.WHITE);
        lblLimpar.setForeground(corFiap);
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        btnLimpar.setBackground(corFiap);
        lblLimpar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        btnCadastrar.setBackground(Color.WHITE);
        lblCadastrar.setForeground(corFiap);
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        btnCadastrar.setBackground(corFiap);
        lblCadastrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        btnCadastrar.requestFocus();
        if(btnCadastrar.isFocusOwner()){
        AdministradorDAO dao = new AdministradorDAO();
        String nome = "", senha = "", turma = "";
        String nome_aluno1 = "", nome_aluno2 = "", nome_aluno3 = "", nome_aluno4 = "", nome_aluno5 = "";
        int rm1 = 0, rm2 = 0, rm3 = 0, rm4 = 0, rm5 = 0;

        if (txtNomeGrupo.getText().isEmpty() || txtComponente1.getText().isEmpty()
                || txtComponente2.getText().isEmpty() || txtComponente3.getText().isEmpty()
                || txtRM1.getText().isEmpty() || txtRM2.getText().isEmpty() || txtRM3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios em branco");
        } else {
            try {

                nome = txtNomeGrupo.getText();
                senha = new String(pwdSenha.getPassword());
                turma = String.valueOf(cbbTurma.getSelectedItem());
                nome_aluno1 = txtComponente1.getText();
                rm1 = Integer.parseInt(txtRM1.getText());
                nome_aluno2 = txtComponente2.getText();
                rm2 = Integer.parseInt(txtRM2.getText());
                nome_aluno3 = txtComponente3.getText();
                rm3 = Integer.parseInt(txtRM3.getText());
                if (!txtComponente4.getText().isEmpty() && !txtRM4.getText().isEmpty()) {
                    nome_aluno4 = txtComponente4.getText();
                    rm4 = Integer.parseInt(txtRM4.getText());
                }
                if (!txtComponente5.getText().isEmpty() && !txtRM5.getText().isEmpty()) {
                    nome_aluno5 = txtComponente5.getText();
                    rm5 = Integer.parseInt(txtRM5.getText());
                }

                Equipe equipe = new Equipe(nome, senha, turma);
                Aluno aluno1 = new Aluno(rm1, nome_aluno1, equipe);
                Aluno aluno2 = new Aluno(rm2, nome_aluno2, equipe);
                Aluno aluno3 = new Aluno(rm3, nome_aluno3, equipe);

                dao.registrarEquipe(equipe);
                dao.registrarAluno(aluno1);
                dao.registrarAluno(aluno2);
                dao.registrarAluno(aluno3);

                if (!txtComponente4.getText().isEmpty() && !txtRM4.getText().isEmpty()) {
                    Aluno aluno4 = new Aluno(rm4, nome_aluno4, equipe);
                    dao.registrarAluno(aluno4);
                }
                if (!txtComponente5.getText().isEmpty() && !txtRM5.getText().isEmpty()) {
                    Aluno aluno5 = new Aluno(rm5, nome_aluno5, equipe);
                    dao.registrarAluno(aluno5);
                }

                JOptionPane.showMessageDialog(this, "Equipe cadastrada com sucesso");
                limpar();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Dados invalidos\n" + e);
                dao.deletarAluno(rm1);
                dao.deletarAluno(rm2);
                dao.deletarAluno(rm3);
                dao.deletarAluno(rm4);
                dao.deletarAluno(rm5);
                dao.deletarEquipe(nome);
                limpar();
            }
            catch (NumberFormatException e2){
                JOptionPane.showMessageDialog(this, "Dados invalidos\n" + e2);
                limpar();
            }
        }
       }
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void txtNomeGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeGrupoFocusLost
        if (!txtNomeGrupo.getText().isEmpty()) {
            String nome = txtNomeGrupo.getText();
            AdministradorDAO dao = new AdministradorDAO();
            if (dao.verificarEquipeExistente(nome)) {
                JOptionPane.showMessageDialog(this, "Nome de equipe já cadastrada");
                txtNomeGrupo.setText("");
                txtNomeGrupo.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNomeGrupoFocusLost

    private void txtRM1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRM1FocusLost
        try {
            if (!txtRM1.getText().isEmpty()) {
                int rm = Integer.parseInt(txtRM1.getText());
                AdministradorDAO dao = new AdministradorDAO();
                if (dao.verificarRMExistente(rm)) {
                    JOptionPane.showMessageDialog(this, "Aluno já cadastrado");
                    txtRM1.setText("");
                    txtRM1.requestFocus();
                }
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_txtRM1FocusLost

    private void txtRM2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRM2FocusLost
        try {
            if (!txtRM2.getText().isEmpty()) {
                int rm = Integer.parseInt(txtRM2.getText());
                AdministradorDAO dao = new AdministradorDAO();
                if (dao.verificarRMExistente(rm)) {
                    JOptionPane.showMessageDialog(this, "Aluno já cadastrado");
                    txtRM2.setText("");
                    txtRM2.requestFocus();
                }
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_txtRM2FocusLost

    private void txtRM3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRM3FocusLost

        try {
            if (!txtRM3.getText().isEmpty()) {
                int rm = Integer.parseInt(txtRM3.getText());
                AdministradorDAO dao = new AdministradorDAO();
                if (dao.verificarRMExistente(rm)) {
                    JOptionPane.showMessageDialog(this, "Aluno já cadastrado");
                    txtRM3.setText("");
                    txtRM3.requestFocus();
                }
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_txtRM3FocusLost

    private void txtRM4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRM4FocusLost
        try {
            if (!txtRM4.getText().isEmpty()) {
                int rm = Integer.parseInt(txtRM4.getText());
                AdministradorDAO dao = new AdministradorDAO();
                if (dao.verificarRMExistente(rm)) {
                    JOptionPane.showMessageDialog(this, "Aluno já cadastrado");
                    txtRM4.setText("");
                    txtRM4.requestFocus();
                }
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_txtRM4FocusLost

    private void txtRM5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRM5FocusLost
        try {
            if (!txtRM5.getText().isEmpty()) {
                int rm = Integer.parseInt(txtRM5.getText());
                AdministradorDAO dao = new AdministradorDAO();
                if (dao.verificarRMExistente(rm)) {
                    JOptionPane.showMessageDialog(this, "Aluno já cadastrado");
                    txtRM5.setText("");
                    txtRM5.requestFocus();
                }
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_txtRM5FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Voltar;
    private javax.swing.JPanel btnCadastrar;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JComboBox<String> cbbTurma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblComponente1;
    private javax.swing.JLabel lblComponente2;
    private javax.swing.JLabel lblComponente3;
    private javax.swing.JLabel lblComponente4;
    private javax.swing.JLabel lblComponente5;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblNomeGrupo;
    private javax.swing.JLabel lblObrigatorio;
    private javax.swing.JLabel lblRM1;
    private javax.swing.JLabel lblRM2;
    private javax.swing.JLabel lblRM3;
    private javax.swing.JLabel lblRM4;
    private javax.swing.JLabel lblRM5;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JLabel logoSpaceCup;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtComponente1;
    private javax.swing.JTextField txtComponente2;
    private javax.swing.JTextField txtComponente3;
    private javax.swing.JTextField txtComponente4;
    private javax.swing.JTextField txtComponente5;
    private javax.swing.JTextField txtNomeGrupo;
    private javax.swing.JTextField txtRM1;
    private javax.swing.JTextField txtRM2;
    private javax.swing.JTextField txtRM3;
    private javax.swing.JTextField txtRM4;
    private javax.swing.JTextField txtRM5;
    // End of variables declaration//GEN-END:variables
}
