/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.spacecup.form;

import br.com.spacecup.dao.FogueteDAO;
import br.com.spacecup.dao.LancamentoDAO;
import br.com.spacecup.modelo.Equipe;
import br.com.spacecup.modelo.Foguete;
import br.com.spacecup.modelo.Lancamento;
import java.awt.Color;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class FormExibirLancamento extends javax.swing.JFrame {

    private Color corFiap = new Color(237, 25, 93);
    private Equipe equipe = null;

    public FormExibirLancamento() {
        initComponents();
    }

    public FormExibirLancamento(Equipe equipe) {
        initComponents();
        this.equipe = equipe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoSpaceCup = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblVoltar = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblDistancia = new javax.swing.JLabel();
        lblAngulo = new javax.swing.JLabel();
        lblVelocidadeVento = new javax.swing.JLabel();
        lblAltitudeMax = new javax.swing.JLabel();
        lblVelocidadeMax = new javax.swing.JLabel();
        lblPico = new javax.swing.JLabel();
        lblTempoProp = new javax.swing.JLabel();
        lblAceleracaoM = new javax.swing.JLabel();
        lblApogeu = new javax.swing.JLabel();
        lblTempoEj = new javax.swing.JLabel();
        lblAltitudeEj = new javax.swing.JLabel();
        lblTaxaDescida = new javax.swing.JLabel();
        lblDuracaoVoo = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        txtDistanciaAlvo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAngulo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtVelocidadeVento = new javax.swing.JTextField();
        txtAltitudeMax = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtVelocidadeMax = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTempoProp = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPicoAceleracao = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtAceleracaoM = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDuracaoVoo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTaxaDescida = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtAltitudeEj = new javax.swing.JTextField();
        txtTempoEj = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtApogeu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAlterar = new javax.swing.JPanel();
        lblAlterar = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JPanel();
        lblExcluir = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JPanel();
        lblPesquisar = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        lblHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        logoSpaceCup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/logo.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("EXIBIR DADOS DE LANÇAMENTO");

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltar.png"))); // NOI18N
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMouseExited(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("DATA");

        lblDistancia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDistancia.setForeground(new java.awt.Color(255, 255, 255));
        lblDistancia.setText("DISTÂNCIA DO ALVO");

        lblAngulo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAngulo.setForeground(new java.awt.Color(255, 255, 255));
        lblAngulo.setText("ÂNGULO DO LANÇAMENTO");

        lblVelocidadeVento.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblVelocidadeVento.setForeground(new java.awt.Color(255, 255, 255));
        lblVelocidadeVento.setText("VELOCIDADE DO VENTO");

        lblAltitudeMax.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAltitudeMax.setForeground(new java.awt.Color(255, 255, 255));
        lblAltitudeMax.setText("ALTITUDE MÁXIMA");

        lblVelocidadeMax.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblVelocidadeMax.setForeground(new java.awt.Color(255, 255, 255));
        lblVelocidadeMax.setText("VELOCIDADE MÁXIMA");

        lblPico.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPico.setForeground(new java.awt.Color(255, 255, 255));
        lblPico.setText("PICO DE ACELERAÇÃO");

        lblTempoProp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTempoProp.setForeground(new java.awt.Color(255, 255, 255));
        lblTempoProp.setText("TEMPO DE PROPULSÃO");

        lblAceleracaoM.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAceleracaoM.setForeground(new java.awt.Color(255, 255, 255));
        lblAceleracaoM.setText("ACELERAÇÃO MÉDIA");

        lblApogeu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblApogeu.setForeground(new java.awt.Color(255, 255, 255));
        lblApogeu.setText("TEMPO ENTRE APOGEU E DESCIDA");

        lblTempoEj.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTempoEj.setForeground(new java.awt.Color(255, 255, 255));
        lblTempoEj.setText("TEMPO DE EJEÇÃO ");

        lblAltitudeEj.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAltitudeEj.setForeground(new java.awt.Color(255, 255, 255));
        lblAltitudeEj.setText("ALTITUDE DE EJEÇÃO ");

        lblTaxaDescida.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTaxaDescida.setForeground(new java.awt.Color(255, 255, 255));
        lblTaxaDescida.setText("TAXA DE DESCIDA");

        lblDuracaoVoo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDuracaoVoo.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracaoVoo.setText("DURAÇÃO DE VOO");

        txtData.setEditable(false);
        txtData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtData.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtData.setSelectionColor(new java.awt.Color(234, 25, 93));

        txtDistanciaAlvo.setEditable(false);
        txtDistanciaAlvo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDistanciaAlvo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDistanciaAlvo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDistanciaAlvo.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("m");

        txtAngulo.setEditable(false);
        txtAngulo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAngulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAngulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAngulo.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("º");

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("m/s");

        txtVelocidadeVento.setEditable(false);
        txtVelocidadeVento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtVelocidadeVento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelocidadeVento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVelocidadeVento.setSelectionColor(new java.awt.Color(234, 25, 93));

        txtAltitudeMax.setEditable(false);
        txtAltitudeMax.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAltitudeMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltitudeMax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAltitudeMax.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("m");

        txtVelocidadeMax.setEditable(false);
        txtVelocidadeMax.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtVelocidadeMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelocidadeMax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVelocidadeMax.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("m/s");

        txtTempoProp.setEditable(false);
        txtTempoProp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTempoProp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTempoProp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTempoProp.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("s");

        txtPicoAceleracao.setEditable(false);
        txtPicoAceleracao.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPicoAceleracao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPicoAceleracao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPicoAceleracao.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Gs");

        txtAceleracaoM.setEditable(false);
        txtAceleracaoM.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAceleracaoM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAceleracaoM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAceleracaoM.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Gs");

        txtDuracaoVoo.setEditable(false);
        txtDuracaoVoo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDuracaoVoo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDuracaoVoo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDuracaoVoo.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("s");

        txtTaxaDescida.setEditable(false);
        txtTaxaDescida.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTaxaDescida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaxaDescida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTaxaDescida.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("m/s");

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("m");

        txtAltitudeEj.setEditable(false);
        txtAltitudeEj.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAltitudeEj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltitudeEj.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAltitudeEj.setSelectionColor(new java.awt.Color(234, 25, 93));

        txtTempoEj.setEditable(false);
        txtTempoEj.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTempoEj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTempoEj.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTempoEj.setSelectionColor(new java.awt.Color(234, 25, 93));

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("s");

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("s");

        txtApogeu.setEditable(false);
        txtApogeu.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtApogeu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApogeu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtApogeu.setSelectionColor(new java.awt.Color(234, 25, 93));

        btnAlterar.setBackground(new java.awt.Color(234, 25, 93));
        btnAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });

        lblAlterar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAlterar.setForeground(new java.awt.Color(255, 255, 255));
        lblAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/foguete.png"))); // NOI18N
        lblAlterar.setText("ALTERAR");

        javax.swing.GroupLayout btnAlterarLayout = new javax.swing.GroupLayout(btnAlterar);
        btnAlterar.setLayout(btnAlterarLayout);
        btnAlterarLayout.setHorizontalGroup(
            btnAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        btnAlterarLayout.setVerticalGroup(
            btnAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnExcluir.setBackground(new java.awt.Color(234, 25, 93));
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });

        lblExcluir.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lblExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExcluir.setText("EXCLUIR");

        javax.swing.GroupLayout btnExcluirLayout = new javax.swing.GroupLayout(btnExcluir);
        btnExcluir.setLayout(btnExcluirLayout);
        btnExcluirLayout.setHorizontalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        btnExcluirLayout.setVerticalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        txtNumero.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumero.setSelectionColor(new java.awt.Color(234, 25, 93));

        lblNumero.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("NUMERO DO LANÇAMENTO");

        btnPesquisar.setBackground(new java.awt.Color(234, 25, 93));
        btnPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
        });

        lblPesquisar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesquisar.setText("PESQUISAR");

        javax.swing.GroupLayout btnPesquisarLayout = new javax.swing.GroupLayout(btnPesquisar);
        btnPesquisar.setLayout(btnPesquisarLayout);
        btnPesquisarLayout.setHorizontalGroup(
            btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnPesquisarLayout.setVerticalGroup(
            btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        txtHora.setEditable(false);
        txtHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtHora.setSelectionColor(new java.awt.Color(234, 25, 93));

        lblHora.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("HORAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblVoltar)
                        .addGap(33, 33, 33)
                        .addComponent(logoSpaceCup)
                        .addGap(57, 57, 57)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAltitudeMax)
                        .addGap(48, 48, 48)
                        .addComponent(txtAltitudeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lblApogeu)
                        .addGap(11, 11, 11)
                        .addComponent(txtApogeu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblVelocidadeMax)
                        .addGap(31, 31, 31)
                        .addComponent(txtVelocidadeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(lblTempoEj)
                        .addGap(100, 100, 100)
                        .addComponent(txtTempoEj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTempoProp)
                        .addGap(26, 26, 26)
                        .addComponent(txtTempoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lblAltitudeEj)
                        .addGap(85, 85, 85)
                        .addComponent(txtAltitudeEj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAceleracaoM)
                        .addGap(42, 42, 42)
                        .addComponent(txtAceleracaoM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lblDuracaoVoo)
                        .addGap(104, 104, 104)
                        .addComponent(txtDuracaoVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(lblHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lblDistancia)
                                .addGap(12, 12, 12)
                                .addComponent(txtDistanciaAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblNumero)
                        .addGap(12, 12, 12)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(lblPico)
                            .addGap(36, 36, 36)
                            .addComponent(txtPicoAceleracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(lblTaxaDescida)
                            .addGap(106, 106, 106)
                            .addComponent(txtTaxaDescida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(lblData)
                            .addGap(8, 8, 8)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAngulo)
                            .addGap(4, 4, 4)
                            .addComponent(txtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lblVelocidadeVento)
                            .addGap(12, 12, 12)
                            .addComponent(txtVelocidadeVento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVoltar)
                            .addComponent(logoSpaceCup)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHora))
                    .addComponent(lblDistancia)
                    .addComponent(txtDistanciaAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAngulo)
                    .addComponent(txtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(lblVelocidadeVento)
                    .addComponent(txtVelocidadeVento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltitudeMax)
                    .addComponent(txtAltitudeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApogeu)
                    .addComponent(txtApogeu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVelocidadeMax)
                    .addComponent(txtVelocidadeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTempoEj)
                    .addComponent(txtTempoEj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempoProp)
                    .addComponent(txtTempoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltitudeEj)
                    .addComponent(txtAltitudeEj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPico)
                    .addComponent(txtPicoAceleracao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaxaDescida)
                    .addComponent(txtTaxaDescida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAceleracaoM)
                    .addComponent(txtAceleracaoM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracaoVoo)
                    .addComponent(txtDuracaoVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        FormMenu fm = new FormMenu(equipe);
        this.dispose();
        fm.setVisible(true);
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void lblVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltarfocus.png"));
        lblVoltar.setIcon(icon);
    }//GEN-LAST:event_lblVoltarMouseEntered

    private void lblVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltar.png"));
        lblVoltar.setIcon(icon);
    }//GEN-LAST:event_lblVoltarMouseExited

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir.setBackground(Color.WHITE);
        lblExcluir.setForeground(corFiap);
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir.setBackground(corFiap);
        lblExcluir.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar.setBackground(Color.WHITE);
        lblAlterar.setForeground(corFiap);
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/foguetefocus.png"));
        lblAlterar.setIcon(icon);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar.setBackground(corFiap);
        lblAlterar.setForeground(Color.WHITE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/foguete.png"));
        lblAlterar.setIcon(icon);
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?");
        if (resp == 0){
        LancamentoDAO dao = new LancamentoDAO();

        if (txtNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um numero de lançamento");
        } else {

            int id = Integer.parseInt(txtNumero.getText());
            FogueteDAO dao2 = new FogueteDAO();
            Foguete foguete = dao2.pesquisarFoguete(equipe);
            if (dao.excluirLancamento(id, foguete)) {
                JOptionPane.showMessageDialog(this, "Lançamento excluido com sucesso!");
                limpar();
                desabilitarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Lançamento não encontrado");
                limpar();
                desabilitarCampos();
            }
        }
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked

        Lancamento lancamento = null;
        LancamentoDAO dao = new LancamentoDAO();

        if (txtNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um numero de lançamento");
            limpar();
        } else {

            try {
                
            int id = Integer.parseInt(txtNumero.getText());
            FogueteDAO dao2 = new FogueteDAO();
            Foguete foguete = dao2.pesquisarFoguete(equipe);
            lancamento = dao.pesquisarLancamento(id, foguete);

            if (lancamento != null) {
                txtAceleracaoM.setText(String.valueOf(lancamento.getAcelMedia()));
                txtAltitudeEj.setText(String.valueOf(lancamento.getAltEje()));
                txtAltitudeMax.setText(String.valueOf(lancamento.getAltMax()));
                txtAngulo.setText(String.valueOf(lancamento.getAngulolancamento()));
                txtApogeu.setText(String.valueOf(lancamento.getTmpApogDesc()));
                SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
                String data = dataFormatada.format(lancamento.getData());
                txtData.setText(data);
                txtHora.setText(lancamento.getHora());
                txtDistanciaAlvo.setText(String.valueOf(lancamento.getDistalvo()));
                txtDuracaoVoo.setText(String.valueOf(lancamento.getDurVoo()));
                txtPicoAceleracao.setText(String.valueOf(lancamento.getPicoAcel()));
                txtTaxaDescida.setText(String.valueOf(lancamento.getTaxDesc()));
                txtTempoEj.setText(String.valueOf(lancamento.getTempoEje()));
                txtTempoProp.setText(String.valueOf(lancamento.getTempoProp()));
                txtVelocidadeMax.setText(String.valueOf(lancamento.getVelMax()));
                txtVelocidadeVento.setText(String.valueOf(lancamento.getVelvento()));
                habilitarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Lançamento não encontrado");
                limpar();
                desabilitarCampos();
            }
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Dados invalidos");
            }
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        btnPesquisar.setBackground(Color.WHITE);
        lblPesquisar.setForeground(corFiap);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        btnPesquisar.setBackground(corFiap);
        lblPesquisar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked

        Lancamento lancamento = getCampos();
        LancamentoDAO dao = new LancamentoDAO();
        if (lancamento != null){            
            if (dao.alterarLancamento(lancamento)) {
                JOptionPane.showMessageDialog(this, "Lançamento alterado com sucesso!");
                limpar();
                desabilitarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Lançamento não encontrado");
                limpar();
                desabilitarCampos();
            }
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void limpar() {
        txtNumero.setText("");
        txtAceleracaoM.setText("");
        txtAltitudeEj.setText("");
        txtAltitudeMax.setText("");
        txtAngulo.setText("");
        txtApogeu.setText("");
        txtData.setText("");
        txtHora.setText("");
        txtDistanciaAlvo.setText("");
        txtDuracaoVoo.setText("");
        txtPicoAceleracao.setText("");
        txtTaxaDescida.setText("");
        txtTempoEj.setText("");
        txtTempoProp.setText("");
        txtVelocidadeMax.setText("");
        txtVelocidadeVento.setText("");
    }

    private Lancamento getCampos() {
        Lancamento lancamento = null;

        if (txtNumero.getText().isEmpty()
                || txtAngulo.getText().isEmpty() || txtDistanciaAlvo.getText().isEmpty()
                || txtVelocidadeMax.getText().isEmpty() || txtAltitudeMax.getText().isEmpty()
                || txtVelocidadeVento.getText().isEmpty() || txtTempoProp.getText().isEmpty()
                || txtPicoAceleracao.getText().isEmpty() || txtAceleracaoM.getText().isEmpty()
                || txtApogeu.getText().isEmpty() || txtTempoEj.getText().isEmpty()
                || txtAltitudeEj.getText().isEmpty() || txtTaxaDescida.getText().isEmpty()
                || txtDuracaoVoo.getText().isEmpty() || txtData.getText().isEmpty()
                || txtHora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else {

            try {

                int id = Integer.parseInt(txtNumero.getText());
                double angulolancamento = Double.parseDouble(txtAngulo.getText());
                double distalvo = Double.parseDouble(txtDistanciaAlvo.getText());
                double velvento = Double.parseDouble(txtVelocidadeVento.getText());
                double altMax = Double.parseDouble(txtAltitudeMax.getText());
                double velMax = Double.parseDouble(txtVelocidadeMax.getText());
                double tempoProp = Double.parseDouble(txtTempoProp.getText());
                double picoAcel = Double.parseDouble(txtPicoAceleracao.getText());
                double acelMedia = Double.parseDouble(txtAceleracaoM.getText());
                double tmpApogDesc = Double.parseDouble(txtApogeu.getText());
                double tempoEje = Double.parseDouble(txtTempoEj.getText());
                double altEje = Double.parseDouble(txtAltitudeEj.getText());
                double taxDesc = Double.parseDouble(txtTaxaDescida.getText());
                double durVoo = Double.parseDouble(txtDuracaoVoo.getText());
                String stdata = txtData.getText();
                SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
                Date data = new Date(dataFormatada.parse(stdata).getTime());
                String hora = txtHora.getText();
                FogueteDAO dao2 = new FogueteDAO();
                Foguete foguete = dao2.pesquisarFoguete(equipe);
                lancamento = new Lancamento(id, angulolancamento, distalvo,
                        velvento, altMax, velMax, tempoProp, picoAcel, acelMedia, tmpApogDesc,
                        tempoEje, altEje, taxDesc, durVoo, data, hora, foguete);

            } catch (ParseException ex) {
                Logger.getLogger(FormRegistrarLancamento.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Dados invalidos");
            }
        }

        return lancamento;
    }

    private void habilitarCampos() {
        txtAceleracaoM.setEditable(true);
        txtAltitudeEj.setEditable(true);
        txtAltitudeMax.setEditable(true);
        txtAngulo.setEditable(true);
        txtApogeu.setEditable(true);
        txtData.setEditable(true);
        txtHora.setEditable(true);
        txtDistanciaAlvo.setEditable(true);
        txtDuracaoVoo.setEditable(true);
        txtPicoAceleracao.setEditable(true);
        txtTaxaDescida.setEditable(true);
        txtTempoEj.setEditable(true);
        txtTempoProp.setEditable(true);
        txtVelocidadeMax.setEditable(true);
        txtVelocidadeVento.setEditable(true);
    }

    private void desabilitarCampos() {
        txtAceleracaoM.setEditable(false);
        txtAltitudeEj.setEditable(false);
        txtAltitudeMax.setEditable(false);
        txtAngulo.setEditable(false);
        txtApogeu.setEditable(false);
        txtData.setEditable(false);
        txtHora.setEditable(false);
        txtDistanciaAlvo.setEditable(false);
        txtDuracaoVoo.setEditable(false);
        txtPicoAceleracao.setEditable(false);
        txtTaxaDescida.setEditable(false);
        txtTempoEj.setEditable(false);
        txtTempoProp.setEditable(false);
        txtVelocidadeMax.setEditable(false);
        txtVelocidadeVento.setEditable(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormExibirLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormExibirLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormExibirLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormExibirLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormExibirLancamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAlterar;
    private javax.swing.JPanel btnExcluir;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAceleracaoM;
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblAltitudeEj;
    private javax.swing.JLabel lblAltitudeMax;
    private javax.swing.JLabel lblAngulo;
    private javax.swing.JLabel lblApogeu;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblDuracaoVoo;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblPico;
    private javax.swing.JLabel lblTaxaDescida;
    private javax.swing.JLabel lblTempoEj;
    private javax.swing.JLabel lblTempoProp;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVelocidadeMax;
    private javax.swing.JLabel lblVelocidadeVento;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JLabel logoSpaceCup;
    private javax.swing.JTextField txtAceleracaoM;
    private javax.swing.JTextField txtAltitudeEj;
    private javax.swing.JTextField txtAltitudeMax;
    private javax.swing.JTextField txtAngulo;
    private javax.swing.JTextField txtApogeu;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDistanciaAlvo;
    private javax.swing.JTextField txtDuracaoVoo;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPicoAceleracao;
    private javax.swing.JTextField txtTaxaDescida;
    private javax.swing.JTextField txtTempoEj;
    private javax.swing.JTextField txtTempoProp;
    private javax.swing.JTextField txtVelocidadeMax;
    private javax.swing.JTextField txtVelocidadeVento;
    // End of variables declaration//GEN-END:variables

}
