/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.spacecup.form;

import br.com.spacecup.dao.EquipeDAO;
import br.com.spacecup.dao.FogueteDAO;
import br.com.spacecup.modelo.Aluno;
import br.com.spacecup.modelo.Equipe;
import br.com.spacecup.modelo.Foguete;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Wesley
 */
public class FormPerfil extends javax.swing.JFrame {

    private Equipe equipe = null;
    private List<Aluno> lista = new ArrayList<>();

    public FormPerfil() {
        initComponents();
    }

    public FormPerfil(Equipe equipe) {
        initComponents();
        this.equipe = equipe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeGrupo = new javax.swing.JLabel();
        lblVoltar = new javax.swing.JLabel();
        lblComponentes = new javax.swing.JLabel();
        lblRM = new javax.swing.JLabel();
        lblComponente1 = new javax.swing.JLabel();
        lblRM1 = new javax.swing.JLabel();
        lblComponente2 = new javax.swing.JLabel();
        lblRM2 = new javax.swing.JLabel();
        lblComponente3 = new javax.swing.JLabel();
        lblRM3 = new javax.swing.JLabel();
        lblComponente4 = new javax.swing.JLabel();
        lblRM4 = new javax.swing.JLabel();
        lblComponente5 = new javax.swing.JLabel();
        lblRM5 = new javax.swing.JLabel();
        lblFoguete = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFoguete2 = new javax.swing.JLabel();
        lblPeso2 = new javax.swing.JLabel();
        lblCor2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblNomeGrupo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblNomeGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/foguetefocus.png"))); // NOI18N
        lblNomeGrupo.setText("_");

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltar.png"))); // NOI18N
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMouseExited(evt);
            }
        });

        lblComponentes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblComponentes.setForeground(new java.awt.Color(255, 255, 255));
        lblComponentes.setText("Componentes");

        lblRM.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblRM.setForeground(new java.awt.Color(255, 255, 255));
        lblRM.setText("RM");

        lblComponente1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente1.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente1.setText("_");

        lblRM1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM1.setForeground(new java.awt.Color(255, 255, 255));
        lblRM1.setText("_");

        lblComponente2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente2.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente2.setText("_");

        lblRM2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM2.setForeground(new java.awt.Color(255, 255, 255));
        lblRM2.setText("_");

        lblComponente3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente3.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente3.setText("_");

        lblRM3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM3.setForeground(new java.awt.Color(255, 255, 255));
        lblRM3.setText("_");

        lblComponente4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente4.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente4.setText("_");

        lblRM4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM4.setForeground(new java.awt.Color(255, 255, 255));
        lblRM4.setText("_");

        lblComponente5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblComponente5.setForeground(new java.awt.Color(255, 255, 255));
        lblComponente5.setText("_");

        lblRM5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRM5.setForeground(new java.awt.Color(255, 255, 255));
        lblRM5.setText("_");

        lblFoguete.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblFoguete.setForeground(new java.awt.Color(255, 255, 255));
        lblFoguete.setText("Foguete:");

        lblPeso.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso.setText("Peso:");

        lblCor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCor.setForeground(new java.awt.Color(255, 255, 255));
        lblCor.setText("Cor:");

        lblFoguete2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblFoguete2.setForeground(new java.awt.Color(255, 255, 255));
        lblFoguete2.setText("_");

        lblPeso2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPeso2.setForeground(new java.awt.Color(255, 255, 255));
        lblPeso2.setText("_");

        lblCor2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblCor2.setForeground(new java.awt.Color(255, 255, 255));
        lblCor2.setText("_");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVoltar)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCor2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPeso2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblFoguete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblFoguete2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomeGrupo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComponentes)
                            .addComponent(lblComponente1)
                            .addComponent(lblComponente4)
                            .addComponent(lblComponente5)
                            .addComponent(lblComponente3)
                            .addComponent(lblComponente2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRM)
                            .addComponent(lblRM1)
                            .addComponent(lblRM3)
                            .addComponent(lblRM2)
                            .addComponent(lblRM5)
                            .addComponent(lblRM4))
                        .addGap(68, 68, 68))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNomeGrupo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFoguete)
                            .addComponent(lblFoguete2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeso)
                            .addComponent(lblPeso2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCor)
                            .addComponent(lblCor2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponentes)
                    .addComponent(lblRM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponente1)
                    .addComponent(lblRM1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponente2)
                    .addComponent(lblRM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponente3)
                    .addComponent(lblRM3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponente4)
                    .addComponent(lblRM4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponente5)
                    .addComponent(lblRM5))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FogueteDAO dao2 = new FogueteDAO();
        Foguete foguete = dao2.pesquisarFoguete(equipe);
        lblFoguete2.setText(foguete.getNome());
        lblPeso2.setText(String.valueOf(foguete.getPeso()));
        lblCor2.setText(foguete.getCor());       
        
        lblNomeGrupo.setText(equipe.getNome().toUpperCase());
        EquipeDAO dao = new EquipeDAO();
        lista = dao.retornarComponentes(equipe);
        int tamanho = lista.size();

        lblComponente1.setText(lista.get(0).getNome());
        lblRM1.setText(String.valueOf(lista.get(0).getRm()));
        lblComponente2.setText(lista.get(1).getNome());
        lblRM2.setText(String.valueOf(lista.get(1).getRm()));
        lblComponente3.setText(lista.get(2).getNome());
        lblRM3.setText(String.valueOf(lista.get(2).getRm()));

        if (tamanho >= 4) {
            lblComponente4.setText(lista.get(3).getNome());
            lblRM4.setText(String.valueOf(lista.get(3).getRm()));
        }

        if (tamanho == 5) {
            lblComponente5.setText(lista.get(4).getNome());
            lblRM5.setText(String.valueOf(lista.get(4).getRm()));
        }

    }//GEN-LAST:event_formWindowOpened

    private void lblVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltar.png"));
        lblVoltar.setIcon(icon);
    }//GEN-LAST:event_lblVoltarMouseExited

    private void lblVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/voltarfocus.png"));
        lblVoltar.setIcon(icon);
    }//GEN-LAST:event_lblVoltarMouseEntered

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        FormMenu fm = new FormMenu(equipe);
        this.dispose();
        fm.setVisible(true);
    }//GEN-LAST:event_lblVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblComponente1;
    private javax.swing.JLabel lblComponente2;
    private javax.swing.JLabel lblComponente3;
    private javax.swing.JLabel lblComponente4;
    private javax.swing.JLabel lblComponente5;
    private javax.swing.JLabel lblComponentes;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblCor2;
    private javax.swing.JLabel lblFoguete;
    private javax.swing.JLabel lblFoguete2;
    private javax.swing.JLabel lblNomeGrupo;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPeso2;
    private javax.swing.JLabel lblRM;
    private javax.swing.JLabel lblRM1;
    private javax.swing.JLabel lblRM2;
    private javax.swing.JLabel lblRM3;
    private javax.swing.JLabel lblRM4;
    private javax.swing.JLabel lblRM5;
    private javax.swing.JLabel lblVoltar;
    // End of variables declaration//GEN-END:variables
}
