/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.spacecup.form;

import br.com.spacecup.modelo.Equipe;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Wesley
 */
public class FormMenu extends javax.swing.JFrame {

   private Color corFiap = new Color(237,25,93);
   private Equipe equipe = null;

    public FormMenu() {
        initComponents();
    }

    public FormMenu(Equipe equipe) {
        initComponents();
        this.equipe = equipe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeGrupo = new javax.swing.JLabel();
        logoSpaceCup = new javax.swing.JLabel();
        btnExibirLancamento = new javax.swing.JPanel();
        lblExibirLancamento = new javax.swing.JLabel();
        btnRegistrarLancamento = new javax.swing.JPanel();
        lblRegistrarLancamento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(461, 205));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeGrupo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblNomeGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeGrupo.setText("_");
        lblNomeGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNomeGrupoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNomeGrupoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNomeGrupoMouseExited(evt);
            }
        });
        jPanel1.add(lblNomeGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        logoSpaceCup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/logo.png"))); // NOI18N
        jPanel1.add(logoSpaceCup, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 77, -1, -1));

        btnExibirLancamento.setBackground(new java.awt.Color(237, 25, 93));
        btnExibirLancamento.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnExibirLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExibirLancamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExibirLancamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExibirLancamentoMouseExited(evt);
            }
        });

        lblExibirLancamento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblExibirLancamento.setForeground(new java.awt.Color(255, 255, 255));
        lblExibirLancamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExibirLancamento.setText("EXIBIR LANÇAMENTOS");

        javax.swing.GroupLayout btnExibirLancamentoLayout = new javax.swing.GroupLayout(btnExibirLancamento);
        btnExibirLancamento.setLayout(btnExibirLancamentoLayout);
        btnExibirLancamentoLayout.setHorizontalGroup(
            btnExibirLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExibirLancamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnExibirLancamentoLayout.setVerticalGroup(
            btnExibirLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExibirLancamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel1.add(btnExibirLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 139, -1, -1));

        btnRegistrarLancamento.setBackground(new java.awt.Color(237, 25, 93));
        btnRegistrarLancamento.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnRegistrarLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarLancamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarLancamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarLancamentoMouseExited(evt);
            }
        });

        lblRegistrarLancamento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRegistrarLancamento.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarLancamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarLancamento.setText("REGISTRAR LANÇAMENTO");

        javax.swing.GroupLayout btnRegistrarLancamentoLayout = new javax.swing.GroupLayout(btnRegistrarLancamento);
        btnRegistrarLancamento.setLayout(btnRegistrarLancamentoLayout);
        btnRegistrarLancamentoLayout.setHorizontalGroup(
            btnRegistrarLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnRegistrarLancamentoLayout.setVerticalGroup(
            btnRegistrarLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel1.add(btnRegistrarLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 75, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bem-vindo,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacecup/fotos/sair.png"))); // NOI18N
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        jPanel1.add(lblSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        FormLogin fm = new FormLogin();
        this.dispose();
        fm.setVisible(true);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/sairfocus.png"));
        lblSair.setIcon(icon);
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/spacecup/fotos/sair.png"));
        lblSair.setIcon(icon);
    }//GEN-LAST:event_lblSairMouseExited

    private void btnRegistrarLancamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarLancamentoMouseEntered
        btnRegistrarLancamento.setBackground(Color.WHITE);
        lblRegistrarLancamento.setForeground(corFiap);
    }//GEN-LAST:event_btnRegistrarLancamentoMouseEntered

    private void btnRegistrarLancamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarLancamentoMouseExited
        btnRegistrarLancamento.setBackground(corFiap);
        lblRegistrarLancamento.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegistrarLancamentoMouseExited

    private void btnExibirLancamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExibirLancamentoMouseEntered
        btnExibirLancamento.setBackground(Color.WHITE);
        lblExibirLancamento.setForeground(corFiap);
    }//GEN-LAST:event_btnExibirLancamentoMouseEntered

    private void btnExibirLancamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExibirLancamentoMouseExited
        btnExibirLancamento.setBackground(corFiap);
        lblExibirLancamento.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExibirLancamentoMouseExited

    private void btnRegistrarLancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarLancamentoMouseClicked
        FormRegistrarLancamento fr = new FormRegistrarLancamento(equipe);
        this.dispose();
        fr.setVisible(true);
    }//GEN-LAST:event_btnRegistrarLancamentoMouseClicked

    private void lblNomeGrupoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNomeGrupoMouseEntered
        lblNomeGrupo.setForeground(corFiap);
    }//GEN-LAST:event_lblNomeGrupoMouseEntered

    private void lblNomeGrupoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNomeGrupoMouseExited
        lblNomeGrupo.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblNomeGrupoMouseExited

    private void lblNomeGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNomeGrupoMouseClicked
        FormPerfil fp = new FormPerfil(equipe);
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_lblNomeGrupoMouseClicked

    private void btnExibirLancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExibirLancamentoMouseClicked
        FormExibirLancamento fe = new FormExibirLancamento(equipe);
        this.dispose();
        fe.setVisible(true);
    }//GEN-LAST:event_btnExibirLancamentoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblNomeGrupo.setText(equipe.getNome().toUpperCase());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnExibirLancamento;
    private javax.swing.JPanel btnRegistrarLancamento;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExibirLancamento;
    private javax.swing.JLabel lblNomeGrupo;
    private javax.swing.JLabel lblRegistrarLancamento;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel logoSpaceCup;
    // End of variables declaration//GEN-END:variables
}
